### ISSUE TITLE
Script Error: File "<stdin>", line 61, AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by TENX-S** [nondanee/vsc-netease-music#104]
macOS 10.15.5
Python 3.8.2

```shell
$ curl https://gist.githubusercontent.com/nondanee/f157bbbccecfe29e48d87273cd02e213/raw | python

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3304  100  3304    0     0   1065      0  0:00:03  0:00:03 --:--:--  1065
vscode 1.48.2 x64
Traceback (most recent call last):
  File "<stdin>", line 61, in <module>
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by nondanee** [comment]
https://gist.github.com/nondanee/f157bbbccecfe29e48d87273cd02e213#file-helper-py-L60
seems `raw.githubusercontent.com` is blocked

**Comment by TENX-S** [comment]
将第60行改写为f-string格式化字符串后可解决问题:
`yarnrc = urllib.urlopen(f'https://raw.githubusercontent.com/Microsoft/{vscode_version[0]}/.yarnrc').read().decode()`

**Comment by nondanee** [comment]
只是换个写法，为啥能解决问题？

**Comment by TENX-S** [comment]
确实只是写法换了，我试了很多次，原先`str.format()`会报错，换成`f-string`就正常了。
原因不知，可能是个例吧。
