### ISSUE TITLE
id为 1985036793 的音乐(无版权)无法播放，并且控件会消失

### ISSUE THREAD

**Issue by dsy4567** [nondanee/vsc-netease-music#125]
![B$AELVAK2_HBPA$28}L8K~5](https://user-images.githubusercontent.com/84607814/198892806-df14544d-2cba-4f93-b40e-a8b4ef70e4c6.png)
![CT{_@D6S{VX9SUXUFQFS`HN](https://user-images.githubusercontent.com/84607814/198893054-fdf28497-8ff8-4a92-af25-5bd13e0850e1.png)

**Comment by dsy4567** [comment]
```
Uncaught (in promise) DOMException: Failed to load because no supported source was found.
workbench.desktop.main.js:608   ERR Cannot read properties of null (reading 'artists'): TypeError: Cannot read properties of null (reading 'artists')
    at Object.artist (C:\Users\dsy45\.vscode\extensions\nondanee.vsc-netease-music-0.0.44\interaction.js:122:24)
    at Object.song (C:\Users\dsy45\.vscode\extensions\nondanee.vsc-netease-music-0.0.44\interaction.js:123:38)
    at receiveMessage (C:\Users\dsy45\.vscode\extensions\nondanee.vsc-netease-music-0.0.44\runtime.js:397:60)
    at p.invoke (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at b.fire (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at u.$onMessage (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:189217)
    at i._doInvokeHandler (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:13680)
    at i._invokeHandler (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:13362)
    at i._receiveRequest (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:12132)
    at i._receiveOneMessage (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:11033)
    at c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:8941
    at p.invoke (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at b.fire (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at c.fire (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19049)
    at c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:17106
    at p.invoke (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at b.fire (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at c.fire (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19049)
    at s._receiveMessage (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:23861)
    at c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:21304
    at p.invoke (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at b.fire (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at b.acceptChunk (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:15880)
    at c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:15010
    at Socket.d (c:\Users\dsy45\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:27128)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```
