### ISSUE TITLE
Error running the python script 

### ISSUE THREAD

**Issue by xiaoweiz** [nondanee/vsc-netease-music#91]
```bash 
curl https://gist.githubusercontent.com/nondanee/f157bbbccecfe29e48d87273cd02e213/raw | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3304  100  3304    0     0   8787      0 --:--:-- --:--:-- --:--:--  8763
vscode 1.46.0 x64
Traceback (most recent call last):
  File "<stdin>", line 60, in <module>
  File "/Users/xiaoweiz/anaconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/xiaoweiz/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/xiaoweiz/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/xiaoweiz/anaconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/xiaoweiz/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/xiaoweiz/anaconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by nondanee** [comment]
看了下现在没问题
你再试试呢
60 行是 https://gist.github.com/nondanee/f157bbbccecfe29e48d87273cd02e213#file-helper-py-L60
访问的是 https://raw.githubusercontent.com/Microsoft/vscode/1.46.0/.yarnrc
可能是当时 vscode 仓库 1.46.0 的 tag 还没打

**Comment by xiaoweiz** [comment]
VS Code crashes after running the script to replace `ffmpeg.dll`. Seems to be related to #86

**Comment by nondanee** [comment]
#86 should be fixed, please check #87

**Comment by xiaoweiz** [comment]
No, the solution in #87 doesn't work any more. 
vscode 1.46.0 
electron 7.3.1 

Here's the header of the crash report. 
```
System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libffmpeg.dylib
  Referenced from: /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: no suitable image found.  Did find:
	/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib: code signature in (/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

**Comment by nondanee** [comment]
Does manual replacement work? https://github.com/nondanee/vsc-netease-music/issues/87#issuecomment-610687595

**Comment by xiaoweiz** [comment]
No.

**Comment by diegofn** [comment]
Hello 

The latest vscode compatible version is 1.45.1
